# we need to base64 encode the user and the password
# echo -n mongouser | base64 && echo -n mongopassword | base64
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-user: bW9uZ291c2Vy
  mongo-password: bW9uZ29wYXNzd29yZA==

